from typing import TypedDict, List, Dict, Any

class AgentState(TypedDict):
    """
    Schema for the LangGraph state machine.
    Holds the input ticker, analysis parameters, intermediate outputs, 
    final reports, and the execution trace logs.
    """
    ticker: str
    market: str                   # 'VN' | 'US'
    pdf_path: str                 # Local path to uploaded PDF report (optional)
    analysis_mode: str            # 'full' | 'technical' | 'fundamental'
    report_language: str          # 'en' | 'vi'
    
    # Raw fetched or parsed data structures
    raw_financials: Dict[str, Any] # Financial statements, ratios, profile metadata
    technical_signals: Dict[str, Any] # Prices series, technical analysis ratios (RSI, MA)
    scraped_news: List[Dict[str, Any]] # Scraped articles with computed sentiment scores
    
    # Agent intermediate summaries & reasoning texts
    fundamental_insights: str
    technical_insights: str
    sentiment_insights: str
    
    # Graph outputs
    final_recommendation: str     # 'BUY' | 'SELL' | 'HOLD'
    final_report_markdown: str    # Fully structured report generated by Synthesis Agent
    
    # Process logger (for UI event streaming)
    logs: List[str]
